Тема 2_лабораторная_1
Kristina-Chun/Lab1 pull request #1
Opened 2024-11-19 17:26 UTC by Kristina-Chun

![image](https://github.com/user-attachments/assets/dfacc241-4eab-4a8c-9294-7ce79c2e2103)

2024-11-25 10:54 UTC, MelekhinEgor requested changes
Добрый день! Необходимо загрузить недостающую задачу для успешного выполнения лабораторной работы! Задача с поиском количества книг на дискете выполнена верно!

2024-11-25 10:54 UTC, MelekhinEgor commented on Лабораторная работа 1/Задание 1.py
Данный файл не относится к заданию лабораторной работы

2024-11-25 10:54 UTC, MelekhinEgor commented on Лабораторная работа 1/Задание 2.py
Не забывайте проставлять пробелы до и после математических операторов

2024-11-25 10:54 UTC, MelekhinEgor commented on Лабораторная работа 1/Задание 3.py
Данный файл дублирует предыдущий, необходимо загрузить верный файл. В рамках лабораторной работы выполнялись две задачи - замена пропущенного значения средним арифметическим и поиск количества книг на дискете. Задачи со средним арифметическим нет среди загруженных файлов

2024-11-28 09:18 UTC, Kristina-Chun commented
Добрый день!
Исправила задания. Вопрос: у меня в курсе, который был подгружен, 3 задания в рамках лабораторной работы 1, а не два.

2024-11-28 09:26 UTC, MelekhinEgor commented
Вам необходимо скачать файл с заданиями на курсе по визуальному программированию - https://dl-ido.spbstu.ru/mod/resource/view.php?id=82568 Там 2 задания в лабораторной работе, а также лабораторных работы всего 2, что соответствует программе курса

2024-11-28 09:27 UTC, MelekhinEgor approved these changes

2025-12-07 15:54 UTC, closed without merging